version: '3'

services:
    # The Application (môi trường chạy project) and The Web Server (máy chủ web - nginx)
    fs_focus:
        container_name: fs_focus
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www
        networks:
            - fs_focus
        volumes:
            - ./:/var/www
            - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
            - "443:443"
        links:
            - database
    # The Database
    database:
        image: mysql:5.7
        restart: always
        container_name: fs_focus_mysql
        networks:
            - fs_focus
        environment: # tham số cấu hình MySQL
            - MYSQL_DATABASE=fs_focus
            - MYSQL_USER=root
            - MYSQL_PASSWORD=binhtk97
            - MYSQL_ROOT_PASSWORD=binhtk97
        volumes:
            - dbdata:/var/lib/mysql/
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        command: # lệnh được chạy khi thực docker-compose run
            mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
            --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
        ports:
            - "3307:3306" # ánh xạ cổng 3306 ở local sang cổng 3306 trong container
        expose:
            - "3307" # expose chỉ định cổng mạng cac container lắng nghe khi chạy

#Docker Networks
networks:
  fs_focus:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local